### ISSUE TITLE
The new abort line thingy is broken

### ISSUE THREAD

**Issue by Riamse** [Riamse/chom-c#4]
```
Traceback (most recent call last):
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 121, in expand
    tok = tok(self, nonterm, tokens)
  File "c.py", line 97, in wrapped
    raise Abort(n)
common.Abort: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 130, in expand
    toks = self.expand(tok)
  File "/home/andrew/vcs/git/chom-c/grammar.py", line 126, in expand
    raise Abort(e.level - 1)
common.Abort: 0
```

**Comment by Riamse** [comment]
Fixed in commit c10a89a.
